"""Export a work order's rendered configuration as Ansible artifacts.

Generates an inventory and a playbook that uses each vendor's official
network config module (e.g. h3c.comware, huawei.datacom, cisco.iosxr,
junipernetworks.junos, arista.eos), matching the platform's intended
northbound automation path (Ansible / StackStorm).
"""
from __future__ import annotations

import io
import zipfile

from sqlalchemy.orm import Session

from app.models.device import Device
from app.models.enums import Vendor
from app.models.workorder import WorkOrder

# vendor -> (ansible_network_os, ansible_connection, config_module)
VENDOR_ANSIBLE = {
    Vendor.H3C: ("h3c.comware.comware", "network_cli", "h3c.comware.comware_config"),
    Vendor.HUAWEI: ("huawei.datacom.ce", "network_cli", "huawei.datacom.ce_config"),
    Vendor.CISCO: ("cisco.iosxr.iosxr", "network_cli", "cisco.iosxr.iosxr_config"),
    Vendor.JUNIPER: (
        "junipernetworks.junos.junos",
        "netconf",
        "junipernetworks.junos.junos_config",
    ),
    Vendor.ARISTA: ("arista.eos.eos", "network_cli", "arista.eos.eos_config"),
    # FRRouting has no universal config module; apply via vtysh over shell.
    Vendor.FRR: ("frr", "ssh", "ansible.builtin.shell"),
}


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in text.splitlines())


def build_inventory(devices: list[Device]) -> str:
    by_vendor: dict[str, list[Device]] = {}
    for d in devices:
        by_vendor.setdefault(d.vendor.value, []).append(d)
    lines = ["# Ansible inventory generated by Bugis", ""]
    for vendor, devs in by_vendor.items():
        net_os, conn, _ = VENDOR_ANSIBLE[Vendor(vendor)]
        lines.append(f"[{vendor}]")
        for d in devs:
            lines.append(
                f"{d.name} ansible_host={d.mgmt_ip} "
                f"ansible_user={d.username or 'admin'}"
            )
        lines.append("")
        lines.append(f"[{vendor}:vars]")
        lines.append(f"ansible_network_os={net_os}")
        lines.append(f"ansible_connection={conn}")
        lines.append("")
    return "\n".join(lines)


def build_playbook(jobs: list[tuple[Device, str, str]]) -> str:
    """jobs: list of (device, operation, rendered_config)."""
    out = [
        "---",
        "# Playbook generated by Bugis - apply circuit configuration",
        "- name: Apply Bugis circuit configuration",
        "  hosts: all",
        "  gather_facts: false",
        "  tasks:",
    ]
    for device, operation, config in jobs:
        _, _, module = VENDOR_ANSIBLE[device.vendor]
        out.append(f"    - name: {operation} config on {device.name}")
        out.append(f"      when: inventory_hostname == '{device.name}'")

        if device.vendor == Vendor.FRR:
            # Apply via vtysh: pipe config lines into the FRR shell.
            cmds = []
            for line in config.splitlines():
                s = line.rstrip()
                if not s or s.startswith(("!", "#")):
                    continue
                cmds.append(f"-c '{s}'")
            out.append(f"      {module}: |")
            out.append(f"        vtysh {' '.join(cmds)}")
            out.append("")
            continue

        out.append(f"      {module}:")
        out.append("        lines:")
        for line in config.splitlines():
            stripped = line.rstrip()
            if not stripped or stripped.startswith(("#", "!", "##")):
                continue
            safe = stripped.replace('"', '\\"')
            out.append(f'          - "{safe}"')
        out.append("")
    return "\n".join(out)


def export_work_order(db: Session, wo: WorkOrder) -> dict:
    jobs: list[tuple[Device, str, str]] = []
    devices: list[Device] = []
    seen = set()
    for job in wo.config_jobs:
        device = db.get(Device, job.device_id)
        if not device or not job.rendered_config:
            continue
        jobs.append((device, job.operation, job.rendered_config))
        if device.id not in seen:
            devices.append(device)
            seen.add(device.id)
    if not jobs:
        raise ValueError("no rendered config jobs")
    return {
        "work_order": wo.code,
        "inventory": build_inventory(devices),
        "playbook": build_playbook(jobs),
        "configs": {
            d.name: cfg for d, _, cfg in jobs
        },
    }


def export_work_order_zip(db: Session, wo: WorkOrder) -> tuple[bytes, str]:
    """Return (zip bytes, filename) for ansible bundle download."""
    data = export_work_order(db, wo)
    code = data["work_order"]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"inventory-{code}.ini", data["inventory"])
        zf.writestr(f"playbook-{code}.yml", data["playbook"])
        readme = (
            f"# Bugis Ansible bundle · work order {code}\n\n"
            "Usage:\n"
            f"  ansible-playbook -i inventory-{code}.ini playbook-{code}.yml\n\n"
            "Requires vendor collections listed in inventory group vars.\n"
        )
        zf.writestr("README.txt", readme)
        for host, cfg in data["configs"].items():
            safe = host.replace("/", "_")
            zf.writestr(f"configs/{safe}.cfg", cfg)
    return buf.getvalue(), f"ansible-{code}.zip"


def export_inventory(db: Session) -> str:
    from sqlalchemy import select

    devices = db.execute(select(Device)).scalars().all()
    return build_inventory(list(devices))
