#!/usr/bin/env bash
# Generate deploy/ha/inventory.env interactively from operator input.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ROOT}/deploy/ha/inventory.env"
EXAMPLE="${ROOT}/deploy/ha/inventory.env.example"

echo "Bugis HA 部署清单生成器"
echo "按提示填写服务器信息（直接回车使用括号内默认值）"
echo ""

read -rp "SSH 用户 [root]: " HA_SSH_USER
HA_SSH_USER="${HA_SSH_USER:-root}"
read -rp "SSH 端口 [22]: " HA_SSH_PORT
HA_SSH_PORT="${HA_SSH_PORT:-22}"

echo ""
echo "=== 数据库（PostgreSQL 主库）==="
read -rp "DB 主库 IP: " HA_DB_HOST
read -rp "DB 端口 [5432]: " HA_DB_PORT
HA_DB_PORT="${HA_DB_PORT:-5432}"
read -rp "DB 绑定地址（内网 IP 或 0.0.0.0 + 防火墙）[0.0.0.0]: " HA_DB_BIND
HA_DB_BIND="${HA_DB_BIND:-0.0.0.0}"
read -rp "PostgreSQL 用户 [bugis]: " POSTGRES_USER
POSTGRES_USER="${POSTGRES_USER:-bugis}"
read -rsp "PostgreSQL 密码: " POSTGRES_PASSWORD
echo ""
read -rp "数据库名 [bugis]: " POSTGRES_DB
POSTGRES_DB="${POSTGRES_DB:-bugis}"
read -rp "DB 从库 IP（可选，无则留空）: " HA_DB_STANDBY_HOST

echo ""
echo "=== 应用节点（至少 2 台）==="
read -rp "App 节点 IP，逗号分隔（第一台为调度主节点）: " HA_APP_HOSTS
read -rp "每台 App 对外 HTTP 端口 [3300]: " HA_APP_HTTP_PORT
HA_APP_HTTP_PORT="${HA_APP_HTTP_PORT:-3300}"
read -rp "Backend /metrics 绑定（内网 IP 或 0.0.0.0 + 防火墙）[0.0.0.0]: " HA_APP_METRICS_BIND
HA_APP_METRICS_BIND="${HA_APP_METRICS_BIND:-0.0.0.0}"

echo ""
echo "=== 负载均衡 ==="
read -rp "LB 节点 IP，逗号分隔: " HA_LB_HOSTS
read -rp "对外 HTTP 端口 [80]: " HA_LB_HTTP_PORT
HA_LB_HTTP_PORT="${HA_LB_HTTP_PORT:-80}"
read -rp "对外 HTTPS 端口 [443]: " HA_LB_HTTPS_PORT
HA_LB_HTTPS_PORT="${HA_LB_HTTPS_PORT:-443}"
read -rp "访问域名（用于 nginx server_name，可填 IP）: " HA_PUBLIC_URL
HA_PUBLIC_URL="${HA_PUBLIC_URL:-_}"

echo ""
echo "=== 可观测性（可选）==="
read -rp "Prometheus/Grafana 节点 IP（留空跳过）: " HA_OBS_HOST

echo ""
echo "=== 密钥 ==="
read -rsp "BUGIS_SECRET_KEY（JWT，所有 App 节点必须相同）: " BUGIS_SECRET_KEY
echo ""
read -rsp "Grafana admin 密码: " GRAFANA_ADMIN_PASSWORD
echo ""
read -rp "生产模式真实下发？[false]: " BUGIS_DRY_RUN
BUGIS_DRY_RUN="${BUGIS_DRY_RUN:-false}"
read -rp "首次部署写入种子数据（租户/驱动目录）？[true]: " BUGIS_RUN_SEED
BUGIS_RUN_SEED="${BUGIS_RUN_SEED:-true}"
read -rp "写入演示专线数据？[false]: " BUGIS_RUN_DEMO
BUGIS_RUN_DEMO="${BUGIS_RUN_DEMO:-false}"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Generated by scripts/ha/generate-inventory.sh on $(date -Iseconds)
HA_SSH_USER=${HA_SSH_USER}
HA_SSH_PORT=${HA_SSH_PORT}

HA_VIP=
HA_PUBLIC_URL=${HA_PUBLIC_URL}

HA_DB_HOST=${HA_DB_HOST}
HA_DB_PORT=${HA_DB_PORT}
HA_DB_BIND=${HA_DB_BIND}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
HA_DB_STANDBY_HOST=${HA_DB_STANDBY_HOST}

HA_APP_HOSTS=${HA_APP_HOSTS}
HA_APP_HTTP_PORT=${HA_APP_HTTP_PORT}
HA_APP_METRICS_BIND=${HA_APP_METRICS_BIND}
HA_APP_METRICS_PORT=8000

HA_LB_HOSTS=${HA_LB_HOSTS}
HA_LB_HTTP_PORT=${HA_LB_HTTP_PORT}
HA_LB_HTTPS_PORT=${HA_LB_HTTPS_PORT}

HA_OBS_HOST=${HA_OBS_HOST}
HA_PROMETHEUS_PORT=9090
HA_GRAFANA_PORT=3000

BUGIS_SECRET_KEY=${BUGIS_SECRET_KEY}
BUGIS_DRY_RUN=${BUGIS_DRY_RUN}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

BUGIS_RUN_SEED=${BUGIS_RUN_SEED}
BUGIS_RUN_DEMO=${BUGIS_RUN_DEMO}
EOF

chmod 600 "$OUT"
echo ""
echo "已写入: $OUT"
echo "下一步: source deploy/ha/inventory.env && ./scripts/ha/deploy-ha.sh"
