"""add bugis sdn controller control-plane (vtep_peers, evpn_routes)

Revision ID: 264781cfb742
Revises: 7d31aaebe160
Create Date: 2026-06-14 11:56:09.929811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '264781cfb742'
down_revision: Union[str, None] = '7d31aaebe160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evpn_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.Enum('IMET', 'MAC_IP', 'IP_PREFIX', 'ETHERNET_SEGMENT', name='evpnroutetype'), nullable=False),
    sa.Column('vni', sa.Integer(), nullable=False),
    sa.Column('rd', sa.String(length=64), nullable=False),
    sa.Column('rt', sa.String(length=64), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=True),
    sa.Column('ip_addr', sa.String(length=64), nullable=True),
    sa.Column('vtep_ip', sa.String(length=64), nullable=False),
    sa.Column('next_hop', sa.String(length=64), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('origin_device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evpn_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evpn_routes_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evpn_routes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evpn_routes_route_type'), ['route_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evpn_routes_vni'), ['vni'], unique=False)
        batch_op.create_index(batch_op.f('ix_evpn_routes_vtep_ip'), ['vtep_ip'], unique=False)

    op.create_table('vtep_peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vtep_ip', sa.String(length=64), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UP', 'DOWN', 'INIT', name='vtepstatus'), nullable=False),
    sa.Column('vnis', sa.String(length=512), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vtep_peers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vtep_peers_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vtep_peers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vtep_peers_vtep_ip'), ['vtep_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vtep_peers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vtep_peers_vtep_ip'))
        batch_op.drop_index(batch_op.f('ix_vtep_peers_id'))
        batch_op.drop_index(batch_op.f('ix_vtep_peers_device_id'))

    op.drop_table('vtep_peers')
    with op.batch_alter_table('evpn_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evpn_routes_vtep_ip'))
        batch_op.drop_index(batch_op.f('ix_evpn_routes_vni'))
        batch_op.drop_index(batch_op.f('ix_evpn_routes_route_type'))
        batch_op.drop_index(batch_op.f('ix_evpn_routes_id'))
        batch_op.drop_index(batch_op.f('ix_evpn_routes_circuit_id'))

    op.drop_table('evpn_routes')
    # ### end Alembic commands ###
