"""snmp interface fields (ifindex, oper_status, discovered_via)

Revision ID: 2c313b861793
Revises: 3ee2f033b53c
Create Date: 2026-06-14 20:07:39.210035
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c313b861793'
down_revision: Union[str, None] = '3ee2f033b53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ifindex', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oper_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('discovered_via', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.drop_column('discovered_via')
        batch_op.drop_column('oper_status')
        batch_op.drop_column('ifindex')

    # ### end Alembic commands ###
