"""device config snapshots

Revision ID: 32a1f53e5bb0
Revises: 2c313b861793
Create Date: 2026-06-15 05:54:29.025846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32a1f53e5bb0'
down_revision: Union[str, None] = '2c313b861793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_config_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_config_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_id'))

    op.drop_table('device_config_snapshots')
    # ### end Alembic commands ###
