"""add endpoint access encapsulation (access_mode, inner_vlan_id)

Revision ID: 3ee2f033b53c
Revises: 264781cfb742
Create Date: 2026-06-14 13:48:40.286396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ee2f033b53c'
down_revision: Union[str, None] = '264781cfb742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Store as VARCHAR (matches str_enum_column / AccessMode values), not PG native enum.
    with op.batch_alter_table('circuit_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'access_mode',
            sa.String(length=32),
            nullable=False,
            server_default='dot1q',
        ))
        batch_op.add_column(sa.Column('inner_vlan_id', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circuit_endpoints', schema=None) as batch_op:
        batch_op.drop_column('inner_vlan_id')
        batch_op.drop_column('access_mode')

    # ### end Alembic commands ###
