"""initial schema

Revision ID: 7d31aaebe160
Revises: 
Create Date: 2026-06-14 11:39:11.246211
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d31aaebe160'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_path'), ['path'], unique=False)

    op.create_table('controllers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('NCE_FABRIC', 'SEERENGINE', 'OPENDAYLIGHT', 'ONOS', name='controllertype'), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('verify_tls', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controllers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_controllers_name'), ['name'], unique=False)

    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('WEBHOOK', 'SLACK', 'DINGTALK', 'WECOM', name='notificationtype'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('min_severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'WARNING', 'INFO', name='alarmseverity'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=255), nullable=True),
    sa.Column('last_dispatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_name'), ['name'], unique=False)

    op.create_table('service_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('service_type', sa.Enum('L2VPN_EVPN', 'L3VPN_EVPN', 'EVPN_VPWS', 'DCI', name='servicetype'), nullable=False),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=False),
    sa.Column('sla_target', sa.String(length=16), nullable=True),
    sa.Column('cos', sa.String(length=16), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_offerings_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_offerings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_offerings_name'), ['name'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('ENTERPRISE', 'HYBRID_CLOUD', 'PUBLIC_CLOUD', 'INTERNAL', name='tenanttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='tenantstatus'), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('cloud_account', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('L2VPN_EVPN', 'L3VPN_EVPN', 'EVPN_VPWS', 'DCI', name='servicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PROVISIONING', 'ACTIVE', 'DEGRADED', 'SUSPENDED', 'DECOMMISSIONED', 'FAILED', name='circuitstatus'), nullable=False),
    sa.Column('vni', sa.Integer(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('vrf_name', sa.String(length=64), nullable=True),
    sa.Column('route_distinguisher', sa.String(length=64), nullable=True),
    sa.Column('route_target', sa.String(length=64), nullable=True),
    sa.Column('esi', sa.String(length=64), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('sla_target', sa.String(length=16), nullable=True),
    sa.Column('cos', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuits_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_circuits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuits_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuits_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bgp_asn', sa.Integer(), nullable=True),
    sa.Column('underlay_prefix', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('delivery_mode', sa.Enum('DIRECT', 'CONTROLLER', name='deliverymode'), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.Enum('H3C', 'HUAWEI', 'JUNIPER', 'ARISTA', 'CISCO', 'FRR', name='vendor'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('SPINE', 'LEAF', 'BORDER_LEAF', 'VTEP', 'PE', 'P', 'RR', 'DCI_GW', 'CPE', name='devicerole'), nullable=False),
    sa.Column('overlay_tech', sa.Enum('VXLAN_EVPN', 'SRMPLS_EVPN', name='overlaytech'), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ONLINE', 'OFFLINE', 'MAINTENANCE', name='devicestatus'), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=64), nullable=False),
    sa.Column('netconf_port', sa.Integer(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('loopback_ip', sa.String(length=64), nullable=True),
    sa.Column('bgp_asn', sa.Integer(), nullable=True),
    sa.Column('sr_node_sid', sa.Integer(), nullable=True),
    sa.Column('is_route_reflector', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_vendor'), ['vendor'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PROVISION', 'MODIFY', 'DECOMMISSION', 'MIGRATE', name='workordertype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)

    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'WARNING', 'INFO', name='alarmseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'CLEARED', name='alarmstatus'), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarms_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_status'), ['status'], unique=False)

    op.create_table('circuit_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('interface_name', sa.String(length=64), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('gateway_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circuit_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuit_endpoints_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuit_endpoints_id'), ['id'], unique=False)

    op.create_table('config_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RENDERED', 'DRY_RUN', 'PUSHING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', name='configjobstatus'), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('rendered_config', sa.Text(), nullable=True),
    sa.Column('rollback_config', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_jobs_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('device_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('admin_up', sa.Boolean(), nullable=False),
    sa.Column('allocated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_interfaces_id'), ['id'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('INTRA_DC', 'DCI', 'ACCESS', 'UPLINK', name='linktype'), nullable=False),
    sa.Column('device_a_id', sa.Integer(), nullable=False),
    sa.Column('device_z_id', sa.Integer(), nullable=False),
    sa.Column('interface_a', sa.String(length=64), nullable=True),
    sa.Column('interface_z', sa.String(length=64), nullable=True),
    sa.Column('capacity_mbps', sa.Integer(), nullable=False),
    sa.Column('reserved_mbps', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_a_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_z_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_name'), ['name'], unique=False)

    op.create_table('telemetry_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('interface_name', sa.String(length=64), nullable=True),
    sa.Column('rx_mbps', sa.Float(), nullable=False),
    sa.Column('tx_mbps', sa.Float(), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('jitter_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('tunnel_state', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_samples_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_samples_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_samples_id'), ['id'], unique=False)

    op.create_table('work_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_events_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_events_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_events_id'))

    op.drop_table('work_order_events')
    with op.batch_alter_table('telemetry_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_samples_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_samples_device_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_samples_circuit_id'))

    op.drop_table('telemetry_samples')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_name'))
        batch_op.drop_index(batch_op.f('ix_links_id'))

    op.drop_table('links')
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_interfaces_id'))

    op.drop_table('device_interfaces')
    with op.batch_alter_table('config_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_jobs_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_config_jobs_id'))

    op.drop_table('config_jobs')
    with op.batch_alter_table('circuit_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuit_endpoints_id'))
        batch_op.drop_index(batch_op.f('ix_circuit_endpoints_circuit_id'))

    op.drop_table('circuit_endpoints')
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_status'))
        batch_op.drop_index(batch_op.f('ix_alarms_severity'))
        batch_op.drop_index(batch_op.f('ix_alarms_kind'))
        batch_op.drop_index(batch_op.f('ix_alarms_id'))
        batch_op.drop_index(batch_op.f('ix_alarms_device_id'))
        batch_op.drop_index(batch_op.f('ix_alarms_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_alarms_circuit_id'))

    op.drop_table('alarms')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_code'))
        batch_op.drop_index(batch_op.f('ix_work_orders_circuit_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_vendor'))
        batch_op.drop_index(batch_op.f('ix_devices_name'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_name'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))
        batch_op.drop_index(batch_op.f('ix_sites_code'))

    op.drop_table('sites')
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuits_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_circuits_name'))
        batch_op.drop_index(batch_op.f('ix_circuits_id'))
        batch_op.drop_index(batch_op.f('ix_circuits_code'))

    op.drop_table('circuits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_code'))

    op.drop_table('tenants')
    with op.batch_alter_table('service_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_offerings_name'))
        batch_op.drop_index(batch_op.f('ix_service_offerings_id'))
        batch_op.drop_index(batch_op.f('ix_service_offerings_code'))

    op.drop_table('service_offerings')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_name'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_id'))

    op.drop_table('notification_channels')
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controllers_name'))
        batch_op.drop_index(batch_op.f('ix_controllers_id'))

    op.drop_table('controllers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_path'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
